version: 2
jobs:
  tests-build:
    working_directory: ~/Curriculum-vitae
    docker:
      - image: circleci/node:lastest
    steps:
      - checkout
      - restore_cache:
        name: Restore Yarn Package Cache
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
        name: Install Dependencies
        command: yarn install
      - run:
        name: Lint the CV
        command: yarn lint
      - run:
        name: Build Prod
        command: production yarn build
  deploy-prod:
    working_directory: ~/Curriculum-vitae
    docker:
      - image: circleci/node:latest
    steps:
      - run:
        name: Deploy on surge
        command: surge --project ./dist --domain clement-martin.surge.sh

workflows:
  version: 2
  tests-build_deploy-prod:
    jobs:
      - tests-build
      # - deploy-prod
      #   requires:
      #     - tests-build
      #   filters:
      #     branches:
      #       only: master
