version: 2
jobs:
  build-deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: surge --project ./dist --domain clement-martin.surge.sh

workflows:
  version: 2
  build_n_deploy:
    jobs:
      - build-deploy
