version: 2
jobs:
  build:
    working_directory: ~/Curriculum-vitae
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn install
      # - run: yarn lint
      - run: yarn build
  deployement:
    production:
      branch: master
      commands:
        - surge --project ./dist --domain clement-martin.surge.sh

workflows:
  version: 2
  build-deployement:
    jobs:
      - build
      - deployement:
        requires:
          - build
