version: 2
jobs:
  tests-build-run:
    working_directory: ~/Curriculum-vitae
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: surge --project ./dist --domain clement-martin.surge.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - tests-build-run
